apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  nameSpace: test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: weddinglalithukarthi@gmail.com  # Change to your email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx   # <-- Use 'class' instead of 'ingressClassName'
