apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-monitor
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: petclinic-app   # <-- matches Service label
  endpoints:
    - port: http           # <-- matches Service port name
      path: /petclinic/actuator/prometheus
      scheme: http
      interval: 30s
      tlsConfig:
        insecureSkipVerify: true   # remove if using valid certs
