apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-app 
  
spec:
  type: ClusterIP
  selector:
    app: petclinic-app
  ports:
    - name: http
      port: 9966
      targetPort: 9966
