trigger:
  - none

variables:
  acrLoginServer: testacr1604.azurecr.io
  imageName: petclinic-app
  imageTag: $(Build.BuildId)
  resourceGroupName: 'nebula-sandbox-karthikeyangopal-5ae5a688'
  aksName: test-aks
  azureServiceConnection: test-azure



stages:
- stage: Build_and_Push
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Login to ACR (Managed Identity)
      inputs:
        azureSubscription: test-azure
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrLoginServer)

    - task: Maven@4
      displayName: Build JAR
      inputs:
        mavenPomFile: pom.xml
        goals: clean package
        options: -DskipTests
        javaHomeOption: JDKVersion
        jdkVersionOption: 17

    - task: AzureCLI@2
      displayName: Build & Push Image to ACR (WIF)
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrLoginServer)

          docker build \
            -t $(acrLoginServer)/$(imageName):$(imageTag) \
            -t $(acrLoginServer)/$(imageName):latest \
            .

          docker push $(acrLoginServer)/$(imageName):$(imageTag)
          docker push $(acrLoginServer)/$(imageName):latest

- stage: Deploy_to_AKS
  dependsOn: Build_and_Push
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - script: |
        # Update the image tag in the correct path
        sed -i 's|testacr090426.azurecr.io/petclinic-app:v1|$(acrLoginServer)/$(imageName):$(imageTag)|g' aks/deploy.yaml
        echo "Updated aks/deploy.yaml with image: $(acrLoginServer)/$(imageName):$(imageTag)"
      displayName: Inject image 

    - task: AzureCLI@2
      displayName: 'Install cert-manager with Helm'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Connect to your AKS cluster
          az aks get-credentials \
            --resource-group '$(resourceGroupName)' \
            --name '$(aksName)'
          
          # Run the helm command (exactly as you wanted)
          helm upgrade --install cert-manager jetstack/cert-manager \
            --repo https://charts.jetstack.io \
            --namespace cert-manager \
            --create-namespace \
            --set installCRDs=true \
            --version v1.9.1 \
            --wait
        
    - task: KubectlInstaller@0
      displayName: 'Verify cert-manager'
      inputs:
        command: 'get'
        arguments: 'pods -n cert-manager' 
  

    - task: Kubernetes@1
      displayName: Deploy using YAML
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: test-azure
        azureResourceGroup: $(resourceGroupName)
        kubernetesCluster: $(aksName)
        command: apply
        useConfigurationFile: true
        configuration: aks/