trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'
variables:
  project_id: 'deft-processor-493715-k5'

steps:
- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
      gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)
      gcloud config set project $(project_id)
      gcloud projects list
    

# Setup Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.0'

- checkout: self

# Run Terraform with the GCP key
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      
      # Navigate to Terraform directory
      # cd terraform-gke
      pwd
      ls -lrt
      cd terraform-gke
      ls -lrt
      # Initialize Terraform
       terraform init -backend-config=backend.tf
  env:
    GOOGLE_APPLICATION_CREDENTIALS: $(gcpKey.secureFilePath)
      
      # # Validate configuration
      # terraform validate
      
      # # Plan the deployment
      # terraform plan -out=tfplan
      
      # # Apply the deployment (auto-approve for CI/CD)
      # terraform apply -auto-approve tfplan
      
      # # Get cluster credentials for kubectl
      # gcloud container clusters get-credentials test-cluster \
      #   --zone europe-west4-c \
      #   --$(project_id)
      
      # # Verify cluster is running
      # kubectl get nodes
  