trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'
variables:
- group: terraform_variables

steps:
- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
      gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)
      gcloud config set project $(project_id)
      gcloud projects list
    


- checkout: self
- task: Bash@3
  displayName: 'Enable Required APIs'
  inputs:
    targetType: 'inline'
    script: |
      gcloud services enable \
        container.googleapis.com \
        cloudresourcemanager.googleapis.com \
        compute.googleapis.com \
        iam.googleapis.com \
        storage-api.googleapis.com \
        --project $(project_id)
      echo "APIs enabled; waiting 30s for propagation..."
      
  env:
    GOOGLE_APPLICATION_CREDENTIALS: $(gcpKey.secureFilePath)

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.9.5'

# Run Terraform with the GCP key
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      
      # Navigate to Terraform directory
      # cd terraform-gke
      pwd
      ls -lrt
      cd terraform-gke
      ls -lrt
      # Initialize Terraform
       terraform init 
       terraform plan -var-file=main.tfvars -var="project_id= $project_id"
       terraform apply -var-file=main.tfvars -var="project_id= $project_id" --auto-approve
  env:
    GOOGLE_APPLICATION_CREDENTIALS: $(gcpKey.secureFilePath)
      
      # # Validate configuration
      # terraform validate
      
      # # Plan the deployment
      # terraform plan -out=tfplan
      
      # # Apply the deployment (auto-approve for CI/CD)
      # terraform apply -auto-approve tfplan
      
      # # Get cluster credentials for kubectl
      # gcloud container clusters get-credentials test-cluster \
      #   --zone europe-west4-c \
      #   --$(project_id)
      
      # # Verify cluster is running
      # kubectl get nodes
  