# azure_pipeline.yaml

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'test-azure'  # Using Managed Identity
  resourceGroupName: 'nebula-sandbox-karthikeyangopal-666c9a16'
  terraformVersion: '1.5.7'
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)/terraform'

stages:
  - stage: Validate
    displayName: 'Validate Terraform'
    jobs:
      - job: Validate
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: AzureCLI@2
            displayName: Check Azure auth
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az account show
                az account get-access-token --resource https://management.azure.com/ >/dev/null
                echo "Auth OK"

          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: $(terraformWorkingDir)
              backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(resourceGroupName)
              backendAzureRmStorageAccountName: 'tfstateacct'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'prod.tfstate'


          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: azurerm
              command: plan
              workingDirectory: $(terraformWorkingDir)
              environmentServiceNameAzureRM: $(azureServiceConnection)
              commandOptions: '-var-file=main.tfvars'

              

  
      # - job: Apply
      #   pool:
      #     vmImage: 'ubuntu-latest'
      #   steps:
      #     - checkout: self

      #     - script: |
      #         cd $(terraformWorkingDir)
      #         terraform apply -var-file=main.tfvars -auto-approve
      #       env:
      #         serviceConnection: test-azure
      #       displayName: 'Terraform Apply'


              