# azure_pipeline.yaml
trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'test-azure'  # Using Managed Identity
  resourceGroupName: 'nebula-sandbox-karthikeyangopal-7114dfd4'
  terraformVersion: '1.5.7'
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)/terraform'

stages:
  - stage: Validate
    displayName: 'Validate Terraform'
    jobs:
      - job: Validate
        pool:
          
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)
          - script: |
              cd $(terraformWorkingDir)
              terraform init -backend=false
              terraform validate
            displayName: 'Terraform Validate'

  - stage: Deploy
    displayName: 'Deploy Infrastructure'
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)

          - script: |
              cd $(terraformWorkingDir)
              terraform plan -var-file=main.tfvars
            env:
              serviceConnection: test-azure
            displayName: 'Terraform Plan'
  
      # - job: Apply
      #   pool:
      #     vmImage: 'ubuntu-latest'
      #   steps:
      #     - checkout: self

      #     - script: |
      #         cd $(terraformWorkingDir)
      #         terraform apply -var-file=main.tfvars -auto-approve
      #       env:
      #         serviceConnection: test-azure
      #       displayName: 'Terraform Apply'


              